[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-b9h7, discord-sessions-prd-1-9 (Session ID: 9fb935885cef942bd4e1548d75314384).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[bot ERROR] Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/hanss/Documents/PycharmProjects/BaseBot/cogs/misc.py", line 56, in help
    cats = [cog.name for cog in self.bot.cogs]
  File "/home/hanss/Documents/PycharmProjects/BaseBot/cogs/misc.py", line 56, in <listcomp>
    cats = [cog.name for cog in self.bot.cogs]
AttributeError: 'str' object has no attribute 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'str' object has no attribute 'name'

[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-m6ss, discord-sessions-prd-1-1 (Session ID: a5897dfb526cbca358e4cb59eb8bf5cf).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[bot ERROR] Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/hanss/Documents/PycharmProjects/BaseBot/cogs/misc.py", line 69, in help
    cats = {cog.lower():name for cog in self.bot.cogs}
  File "/home/hanss/Documents/PycharmProjects/BaseBot/cogs/misc.py", line 69, in <dictcomp>
    cats = {cog.lower():name for cog in self.bot.cogs}
NameError: name 'name' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'name' is not defined

[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-b6bg, discord-sessions-prd-1-7 (Session ID: 2072759bd342e2b6d75d7dd01d49cd62).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[bot ERROR] Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/hanss/Documents/PycharmProjects/BaseBot/cogs/misc.py", line 113, in help
    return await ctx.send(d)
  File "/usr/lib/python3.6/site-packages/discord/abc.py", line 764, in send
    data = yield from state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/usr/lib/python3.6/site-packages/discord/http.py", line 212, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Cannot send an empty message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400): Cannot send an empty message

[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-j1xb, discord-sessions-prd-1-4 (Session ID: 4e1feb15fd2da33bd25057d70dedacc4).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-nk6n, discord-sessions-prd-1-2 (Session ID: f7faed80d732c1a04e771304a96d3318).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-t70d, discord-sessions-prd-1-3 (Session ID: b7d96638080154344a410ee3152cb905).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-tw68, discord-sessions-prd-1-8 (Session ID: 526663b934c855a36aac5428240e4ad2).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-662d, discord-sessions-prd-1-6 (Session ID: f0388e2aa6f8902a3ad81a1ed8df36a8).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-9spd, discord-sessions-prd-1-15 (Session ID: d5abc9bbcf475862bec292eeecb8de61).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[bot ERROR] Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/hanss/Documents/PycharmProjects/BaseBot/cogs/misc.py", line 116, in help
    d = self.get_help(ctx, cmd, name=cmd_name)
TypeError: get_help() got an unexpected keyword argument 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: get_help() got an unexpected keyword argument 'name'

[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-nlb5, discord-sessions-prd-1-9 (Session ID: 6b3197e26e4c31de20e5964769b36454).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[bot ERROR] Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/hanss/Documents/PycharmProjects/BaseBot/cogs/core.py", line 26, in reload_all
    importlib.reload(sys.modules['cogs.util'])
KeyError: 'cogs.util'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 889, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'cogs.util'

[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-t70d, discord-sessions-prd-1-10 (Session ID: 598d10224b484cf42b18964861cee10d).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-d965, discord-sessions-prd-1-14 (Session ID: af9a2f35ae1687c91d280211d1d581fb).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
[bot INFO] Loaded cog cogs.misc.
[bot INFO] Loaded cog cogs.git.
[bot INFO] Loaded cog cogs.core.
[bot INFO] Loaded 3 cogs
[discord.client INFO] logging in using static token
[discord.gateway INFO] Shard ID 0 has sent the IDENTIFY payload.
[discord.gateway INFO] Shard ID 0 has connected to Gateway: gateway-prd-main-sfmv, discord-sessions-prd-1-2 (Session ID: ff14c631aedc34816a226a0c47bb5ecd).
[bot INFO] Connected to Discord
[bot INFO] Guilds  : 2
[bot INFO] Users   : 36
[bot INFO] Channels: 27
[discord.client INFO] Cleaning up event loop.
[discord.gateway INFO] Websocket closed with 1000 (), cannot reconnect.
[discord.client INFO] Cleaning up after 5 tasks
